name: simple_result
version: 1.0.8
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lint: ^2.0.1
  test: ^1.22.1
