name: simple_result
version: 1.1.0
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:  
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  freezed_annotation: ^2.4.1
  
dev_dependencies:
  build_runner: ^2.4.8
  collection: ^1.18.0
  equatable: ^2.0.5
  freezed: ^2.4.6
  lint: ^2.3.0
  meta: ^1.11.0
  test: ^1.25.2
